---
language: ruby

rvm:
  - 1.9.3
  - 2.1.0
  - 2.3.1

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.1.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.2.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.3.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.4.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.5.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.6.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.7.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.8.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.0.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.1.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.2.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.3.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.4.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.5.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.6.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.7.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.8.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4" CHECK=test
    - PUPPET_GEM_VERSION="~> 4" CHECK=rubocop

sudo: false

bundler_args: '--without system_tests development'

script: 'SPEC_OPTS="--format documentation" bundle exec rake $CHECK'

# only do rubocop tests with the newest version of ruby so that we are
# following the most up to date style requirements.
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.1.0" CHECK=test
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.2.0" CHECK=test
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.3.0" CHECK=test
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.4.0" CHECK=test
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4" CHECK=rubocop
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 4" CHECK=rubocop
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.1.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.2.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.3.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.4.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.5.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.6.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.7.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.8.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes" CHECK=test

notifications:
  email: false
