---
language: ruby

sudo: false

bundler_args: '--without system_tests development'

script: 'SPEC_OPTS="--format documentation" bundle exec rake $CHECK'

matrix:
  fast_finish: true
  include:
  - rvm: 2.4.4
    env: PUPPET_GEM_VERSION="~> 5" CHECK=test
  - rvm: 2.4.4
    env: PUPPET_GEM_VERSION="~> 5" CHECK=build DEPLOY_TO_FORGE=yes
  - rvm: 2.5.3
    env: PUPPET_GEM_VERSION="~> 6" check=test
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="centos-6" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="centos-6" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="rhel8-8" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="rhel-8" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
- rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="debian-8" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="debian-8" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="debian-9" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="debian-9" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="fedora-29" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="fedora-29" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="fedora-30" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="fedora-30" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1604" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1604" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1804" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1804" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker

notifications:
  email: false
deploy:
  provider: puppetforge
  user: sgnl05
  password:
    secure: "tnY3nJ3CVgqwxPvcqhQVUSq5KrOuvaJgz+IiGFqTesdNaL8z+T/VUgYD0uYvA/QSXNUGa+FWo4GCANWz7p7jO8sKJm/+ngwKyPLDTTUZ97cTndsliwxiDQxUqnCSkXfEGd6+RLqWtjqUe8+dHrXkjYdLB616iJtTv8l9ERENkYSPKaBJrvDilljZHT2GjnRjc7yIEf40N2pMqBCqjoJbvzgstzQDkznrRd9TTmTPleFK7iTkDoiUwRrlthYqIz7TpkDC2XhM9VTq7u4bOk7TfG9zQjImAYV8SZRb2t06tqKMn7apcdCZ0dOYwC9H/GfOrz2fHFNBHh/lqz01xG/0vLdbVJkW5/I8tTkwqeNAxq8FcsSqFpFQ3IIsqTobIZRHUPtqWsI1gYz0+UknikILjt685+CBUki/JrvoFv31EuX5B58E/57LQDP8k4xzvtyAXc0uSqhkaR/P1Usikx1UJ18VghlHRbMIpw509MAt6V0jPk0nrY9UX8xsxeqdBxcDJ7KHAbBfqpcDiANgYLdt9H/mxAqGgS0oJaHDeSLyL0j36k+CBLw5PLgYwvtmjpfRsP8oLdFJlNFQ81IdbTPFNaEmAd71zxO/XHQsmlUow9sNjGPf5E5pgZRbpODdIp11eFbn+tLYa+zAf/iYQa4p5E5LCuwMOoTZXHI6TYE92i8="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
