---
language: ruby

rvm:
  - 1.9.3
  - 2.1.0
  - 2.3.1

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.1.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.2.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.3.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.4.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.5.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.6.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.7.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.8.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 3.8.0" CHECK=build DEPLOY_TO_FORGE=yes
    - PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.0.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.1.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.2.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.3.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.4.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.5.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.6.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.7.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.8.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.9.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4" CHECK=test

sudo: false

bundler_args: '--without system_tests development'

script: 'SPEC_OPTS="--format documentation" bundle exec rake $CHECK'

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.1.0" CHECK=test
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.2.0" CHECK=test
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.3.0" CHECK=test
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.4.0" CHECK=test
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.8.0" CHECK=build DEPLOY_TO_FORGE=yes
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.9.0" CHECK=test
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.1.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.2.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.3.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.4.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.5.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.6.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.7.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.8.0" CHECK=test
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.8.0" CHECK=build DEPLOY_TO_FORGE=yes
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes" CHECK=test

notifications:
  email: false
deploy:
  provider: puppetforge
  user: sgnl05
  password:
    secure: "tnY3nJ3CVgqwxPvcqhQVUSq5KrOuvaJgz+IiGFqTesdNaL8z+T/VUgYD0uYvA/QSXNUGa+FWo4GCANWz7p7jO8sKJm/+ngwKyPLDTTUZ97cTndsliwxiDQxUqnCSkXfEGd6+RLqWtjqUe8+dHrXkjYdLB616iJtTv8l9ERENkYSPKaBJrvDilljZHT2GjnRjc7yIEf40N2pMqBCqjoJbvzgstzQDkznrRd9TTmTPleFK7iTkDoiUwRrlthYqIz7TpkDC2XhM9VTq7u4bOk7TfG9zQjImAYV8SZRb2t06tqKMn7apcdCZ0dOYwC9H/GfOrz2fHFNBHh/lqz01xG/0vLdbVJkW5/I8tTkwqeNAxq8FcsSqFpFQ3IIsqTobIZRHUPtqWsI1gYz0+UknikILjt685+CBUki/JrvoFv31EuX5B58E/57LQDP8k4xzvtyAXc0uSqhkaR/P1Usikx1UJ18VghlHRbMIpw509MAt6V0jPk0nrY9UX8xsxeqdBxcDJ7KHAbBfqpcDiANgYLdt9H/mxAqGgS0oJaHDeSLyL0j36k+CBLw5PLgYwvtmjpfRsP8oLdFJlNFQ81IdbTPFNaEmAd71zxO/XHQsmlUow9sNjGPf5E5pgZRbpODdIp11eFbn+tLYa+zAf/iYQa4p5E5LCuwMOoTZXHI6TYE92i8="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
